// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwZrWhT5a6HBpYMzkQFtm-f0QiKzQpUC0',
    appId: '1:248504485245:web:ffe4bc93685565c338f814',
    messagingSenderId: '248504485245',
    projectId: 'sphere-dd78f',
    authDomain: 'sphere-dd78f.firebaseapp.com',
    storageBucket: 'sphere-dd78f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoDMeXVU7rAAvs9qG_8jVpFyEvFNAQrgs',
    appId: '1:248504485245:android:289d5c504e2daccb38f814',
    messagingSenderId: '248504485245',
    projectId: 'sphere-dd78f',
    storageBucket: 'sphere-dd78f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwimSRv0QqFuIKBrm8ngE6Ks6lY1rZHZY',
    appId: '1:248504485245:ios:a2932bca922ecf0e38f814',
    messagingSenderId: '248504485245',
    projectId: 'sphere-dd78f',
    storageBucket: 'sphere-dd78f.appspot.com',
    iosBundleId: 'com.example.sphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwZrWhT5a6HBpYMzkQFtm-f0QiKzQpUC0',
    appId: '1:248504485245:web:84ae2547ca17c2c138f814',
    messagingSenderId: '248504485245',
    projectId: 'sphere-dd78f',
    authDomain: 'sphere-dd78f.firebaseapp.com',
    storageBucket: 'sphere-dd78f.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwimSRv0QqFuIKBrm8ngE6Ks6lY1rZHZY',
    appId: '1:248504485245:ios:a2932bca922ecf0e38f814',
    messagingSenderId: '248504485245',
    projectId: 'sphere-dd78f',
    storageBucket: 'sphere-dd78f.appspot.com',
    iosBundleId: 'com.example.sphere',
  );

}